logging:
  level:
    root: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:~/vincenzo;DB_CLOSE_ON_EXIT=TRUE;DB_CLOSE_DELAY=-1;MODE=MYSQL # DATABASE_TO_UPPER=false # pick
    username: vincenzo
    password: vincenzo
    hikari:
#      jdbc-url:
      pool-name: TEST-SPRING-BOOT-JPA
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 30
      platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
#    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # deprecated
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true # data.sql이 hibernate보다 먼저 실행되지 않도록 지연
  batch:
    jdbc:
      initialize-schema: ALWAYS
#      table-prefix: BATCH_{Custom}
